services:
  teampass-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: teampass-local:latest
    container_name: teampass-app
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: teampass
      DB_USER: teampass
      DB_PASSWORD: change_me_teampass_db_password
      INSTALL_MODE: manual
      TEAMPASS_URL: http://localhost:8080
    volumes:
      - teampass-sk:/var/www/html/sk
      - teampass-files:/var/www/html/files
      - teampass-upload:/var/www/html/upload
    ports:
      - 8080:80
    networks:
      - teampass-network
    depends_on:
      - db

  db:
    image: mariadb:11.2
    container_name: teampass-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: change_me_root_password
      MARIADB_DATABASE: teampass
      MARIADB_USER: teampass
      MARIADB_PASSWORD: change_me_teampass_db_password
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
    volumes:
      - teampass-db:/var/lib/mysql
      - ./docker/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - teampass-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_allowed_packet=64M

networks:
  teampass-network:


volumes:
  teampass-sk:
  teampass-files:
  teampass-upload:
  teampass-db:
