blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/nilsteampassnet/TeamPass/discussions
    about: Please ask questions and start discussions here, not as issues.
